cflags   = '-ggdb -DDEBUG -O2'
#cflags   = '-ggdb'
includes = ['/Developer/usr/include', '../client/c', '../']
ldflags  = ['']
libpath  = ['/Developer/usr/lib', '../client/c']
libs	 = ['m']

env = Environment(CCFLAGS=cflags, CPPPATH=includes, LINKFLAGS=ldflags, LIBPATH=libpath, LIBS=libs)

#files = Glob("*.c")
#for fn in files:
#	env.Program(fn)

env.Program("test", ["test.c", "../client/c/libmemlink.a"])

env = Environment(CCFLAGS=cflags, CPPPATH=includes, LINKFLAGS=ldflags, LIBPATH=libpath, LIBS=['m'])
env.Program('testmask', ["testmask.c", '../utils.c', '../logfile.c', '../serial.c', '../zzmalloc.c'])
