/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.googlecode.memlink;

public class MemLinkWcInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MemLinkWcInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MemLinkWcInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      memlink.memlink_wcinfo_free(this);
      if (swigCMemOwn) {
        swigCMemOwn = false;
        memlinkJNI.delete_MemLinkWcInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setConncount(int value) {
    memlinkJNI.MemLinkWcInfo_conncount_set(swigCPtr, this, value);
  }

  public int getConncount() {
    return memlinkJNI.MemLinkWcInfo_conncount_get(swigCPtr, this);
  }

  public void setRoot(MemLinkWcItem value) {
    memlinkJNI.MemLinkWcInfo_root_set(swigCPtr, this, MemLinkWcItem.getCPtr(value), value);
  }

  public MemLinkWcItem getRoot() {
    long cPtr = memlinkJNI.MemLinkWcInfo_root_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MemLinkWcItem(cPtr, false);
  }

  public MemLinkWcInfo() {
    this(memlinkJNI.new_MemLinkWcInfo(), true);
  }

}
