import sys, os, subprocess

java_home		= '/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0'
java_includes	= [os.path.join(java_home, 'include'), os.path.join(java_home, 'include/linux')]
#java_libs		= os.path.join(java_home, 'lib')


os.system('swig -java -o memlink_client_java.c ../c/memlink_client.i')

cflags   = '-ggdb'
includes = ['.', '../../', '../c/', '/Developer/usr/include'] + java_includes
libpath  = ['.']
libs	 = ''
files    = ['../../zzmalloc.c', '../../serial.c', '../../logfile.c', '../../utils.c', 
			'../c/memlink_client.c', 'memlink_client_java.c']

env = Environment(CCFLAGS=cflags, CPPPATH=includes, LIBPATH=libpath, LIBS=libs)
env.SharedLibrary("memlink", files)

