import sys, os, subprocess

x = subprocess.Popen('/usr/bin/python2.6-config --includes', stdout=subprocess.PIPE, shell=True)
python_includes = x.stdout.read().strip().split()

x = subprocess.Popen('/usr/bin/python2.6-config --libs', stdout=subprocess.PIPE, shell=True)
python_libs = x.stdout.read().strip().split()

x = subprocess.Popen('/usr/bin/python2.6-config --ldflags', stdout=subprocess.PIPE, shell=True)
python_ldflags = x.stdout.read()

os.system('swig -python -o memlink_client_python.c ../c/memlink_client.i')

cflags   = '-ggdb'
includes = ['.', '../../', '../c/', '/Developer/usr/include'] + python_includes
ldflags  = python_ldflags
libpath  = ['.']
libs	 = python_libs
files    = ['../../zzmalloc.c', '../../serial.c', '../../logfile.c', '../../utils.c', 
			'../c/memlink_client.c', 'memlink_client_python.c']

env = Environment(CCFLAGS=cflags, CPPPATH=includes, LINKFLAGS=ldflags, LIBPATH=libpath, LIBS=libs)
env.SharedLibrary("memlink", files)

