#cflags   = '-ggdb -DRANGE_MASK_STR'
#cflags   = '-ggdb -DDEBUG -DRANGE_MASK_STR'
cflags   = '-ggdb -Wall -O2'
#cflags   = '-ggdb -DDEBUG -Wall'
includes = ['.', '../../', '/Developer/usr/include']
libpath  = ['.']
libs	 = ['m']
comfiles = ['../../zzmalloc.c', '../../serial.c', '../../logfile.c', '../../utils.c']
prgfiles = comfiles + ['memlink_client.c', 'test.c']
libfiles = comfiles + ['memlink_client.c']

env = Environment(CCFLAGS=cflags, CPPPATH=includes, LIBPATH=libpath, LIBS=libs)
env.SharedLibrary("memlink", libfiles)
env.StaticLibrary("memlink", libfiles)

env.Program("client", prgfiles)
