cflags   = '-ggdb -DDEBUG'
#cflags   = '-ggdb'
includes = ['/Developer/usr/include', '../client/c', '../']
ldflags  = []
libpath  = ['/Developer/usr/lib', '../client/c']
libs	 = ['memlink']

env = Environment(CCFLAGS=cflags, CPPPATH=includes, LINKFLAGS=ldflags, LIBPATH=libpath, LIBS=libs)

files = Glob("*.c")
for fn in files:
	env.Program(fn)
