import os, sys

cflags    = '-ggdb -DDEBUG -O2 -pthread'
#cflags   = '-ggdb'
includes  = ['../client/c', '../']
ldflags   = ['']
libpath   = ['../client/c']
libs	  = ['m', 'pthread']
perffiles = ['perf.c', '../client/c/libmemlink.a']

env = Environment(CCFLAGS=cflags, CPPPATH=includes, LINKFLAGS=ldflags, LIBPATH=libpath, LIBS=libs)
env.Program("perf", perffiles)
