/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.googlecode.memlink;

public class MemLinkInsertKey {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MemLinkInsertKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MemLinkInsertKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cmemlinkJNI.delete_MemLinkInsertKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSum_val_size(long value) {
    cmemlinkJNI.MemLinkInsertKey_sum_val_size_set(swigCPtr, this, value);
  }

  public long getSum_val_size() {
    return cmemlinkJNI.MemLinkInsertKey_sum_val_size_get(swigCPtr, this);
  }

  public void setKey(String value) {
    cmemlinkJNI.MemLinkInsertKey_key_set(swigCPtr, this, value);
  }

  public String getKey() {
    return cmemlinkJNI.MemLinkInsertKey_key_get(swigCPtr, this);
  }

  public void setKeylen(short value) {
    cmemlinkJNI.MemLinkInsertKey_keylen_set(swigCPtr, this, value);
  }

  public short getKeylen() {
    return cmemlinkJNI.MemLinkInsertKey_keylen_get(swigCPtr, this);
  }

  public void setValnum(long value) {
    cmemlinkJNI.MemLinkInsertKey_valnum_set(swigCPtr, this, value);
  }

  public long getValnum() {
    return cmemlinkJNI.MemLinkInsertKey_valnum_get(swigCPtr, this);
  }

  public void setVallist(MemLinkInsertVal value) {
    cmemlinkJNI.MemLinkInsertKey_vallist_set(swigCPtr, this, MemLinkInsertVal.getCPtr(value), value);
  }

  public MemLinkInsertVal getVallist() {
    long cPtr = cmemlinkJNI.MemLinkInsertKey_vallist_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MemLinkInsertVal(cPtr, false);
  }

  public void setTail(MemLinkInsertVal value) {
    cmemlinkJNI.MemLinkInsertKey_tail_set(swigCPtr, this, MemLinkInsertVal.getCPtr(value), value);
  }

  public MemLinkInsertVal getTail() {
    long cPtr = cmemlinkJNI.MemLinkInsertKey_tail_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MemLinkInsertVal(cPtr, false);
  }

  public void setNext(MemLinkInsertKey value) {
    cmemlinkJNI.MemLinkInsertKey_next_set(swigCPtr, this, MemLinkInsertKey.getCPtr(value), value);
  }

  public MemLinkInsertKey getNext() {
    long cPtr = cmemlinkJNI.MemLinkInsertKey_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MemLinkInsertKey(cPtr, false);
  }

  public MemLinkInsertKey(String key) {
    //this(cmemlinkJNI.new_MemLinkInsertKey(), true);
	this(cmemlinkJNI.memlink_ikey_create(key, key.length()), true);
  }
  public int add(MemLinkInsertVal valobj) {
      return cmemlinkJNI.memlink_ikey_add_value(swigCPtr, this, MemLinkInsertVal.getCPtr(valobj), valobj);
  }


}
