/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.googlecode.memlink;

public class MemLinkInsertVal {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MemLinkInsertVal(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MemLinkInsertVal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cmemlinkJNI.delete_MemLinkInsertVal(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(String value) {
    cmemlinkJNI.MemLinkInsertVal_value_set(swigCPtr, this, value);
  }

  public String getValue() {
    return cmemlinkJNI.MemLinkInsertVal_value_get(swigCPtr, this);
  }

  public void setValuelen(short value) {
    cmemlinkJNI.MemLinkInsertVal_valuelen_set(swigCPtr, this, value);
  }

  public short getValuelen() {
    return cmemlinkJNI.MemLinkInsertVal_valuelen_get(swigCPtr, this);
  }

  public void setMaskstr(String value) {
    cmemlinkJNI.MemLinkInsertVal_maskstr_set(swigCPtr, this, value);
  }

  public String getMaskstr() {
    return cmemlinkJNI.MemLinkInsertVal_maskstr_get(swigCPtr, this);
  }

  public void setMaskarray(SWIGTYPE_p_unsigned_int value) {
    cmemlinkJNI.MemLinkInsertVal_maskarray_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getMaskarray() {
    long cPtr = cmemlinkJNI.MemLinkInsertVal_maskarray_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setMasknum(short value) {
    cmemlinkJNI.MemLinkInsertVal_masknum_set(swigCPtr, this, value);
  }

  public short getMasknum() {
    return cmemlinkJNI.MemLinkInsertVal_masknum_get(swigCPtr, this);
  }

  public void setPos(int value) {
    cmemlinkJNI.MemLinkInsertVal_pos_set(swigCPtr, this, value);
  }

  public int getPos() {
    return cmemlinkJNI.MemLinkInsertVal_pos_get(swigCPtr, this);
  }

  public void setNext(MemLinkInsertVal value) {
    cmemlinkJNI.MemLinkInsertVal_next_set(swigCPtr, this, MemLinkInsertVal.getCPtr(value), value);
  }

  public MemLinkInsertVal getNext() {
    long cPtr = cmemlinkJNI.MemLinkInsertVal_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MemLinkInsertVal(cPtr, false);
  }

  public MemLinkInsertVal(String value, String maskstr, int pos) {
    //this(cmemlinkJNI.new_MemLinkInsertVal(), true);
	this(cmemlinkJNI.memlink_ival_create(value, value.length(), maskstr, pos), true);
  }

}
