/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.googlecode.memlink;

public class MemLinkResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MemLinkResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MemLinkResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      memlink.memlink_result_free(this);
      if (swigCMemOwn) {
        swigCMemOwn = false;
        memlinkJNI.delete_MemLinkResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCount(int value) {
    memlinkJNI.MemLinkResult_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return memlinkJNI.MemLinkResult_count_get(swigCPtr, this);
  }

  public void setValuesize(int value) {
    memlinkJNI.MemLinkResult_valuesize_set(swigCPtr, this, value);
  }

  public int getValuesize() {
    return memlinkJNI.MemLinkResult_valuesize_get(swigCPtr, this);
  }

  public void setMasksize(int value) {
    memlinkJNI.MemLinkResult_masksize_set(swigCPtr, this, value);
  }

  public int getMasksize() {
    return memlinkJNI.MemLinkResult_masksize_get(swigCPtr, this);
  }

  public void setRoot(MemLinkItem value) {
    memlinkJNI.MemLinkResult_root_set(swigCPtr, this, MemLinkItem.getCPtr(value), value);
  }

  public MemLinkItem getRoot() {
    long cPtr = memlinkJNI.MemLinkResult_root_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MemLinkItem(cPtr, false);
  }

  public MemLinkResult() {
    this(memlinkJNI.new_MemLinkResult(), true);
  }

}
