/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.googlecode.memlink;

public class MemLinkInsertMkv {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MemLinkInsertMkv(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MemLinkInsertMkv obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
	  cmemlink.memlink_imkv_destroy(this);
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cmemlinkJNI.delete_MemLinkInsertMkv(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSum_size(long value) {
    cmemlinkJNI.MemLinkInsertMkv_sum_size_set(swigCPtr, this, value);
  }

  public long getSum_size() {
    return cmemlinkJNI.MemLinkInsertMkv_sum_size_get(swigCPtr, this);
  }

  public void setKeynum(long value) {
    cmemlinkJNI.MemLinkInsertMkv_keynum_set(swigCPtr, this, value);
  }

  public long getKeynum() {
    return cmemlinkJNI.MemLinkInsertMkv_keynum_get(swigCPtr, this);
  }

  public void setKindex(int value) {
    cmemlinkJNI.MemLinkInsertMkv_kindex_set(swigCPtr, this, value);
  }

  public int getKindex() {
    return cmemlinkJNI.MemLinkInsertMkv_kindex_get(swigCPtr, this);
  }

  public void setVindex(int value) {
    cmemlinkJNI.MemLinkInsertMkv_vindex_set(swigCPtr, this, value);
  }

  public int getVindex() {
    return cmemlinkJNI.MemLinkInsertMkv_vindex_get(swigCPtr, this);
  }

  public void setKeylist(MemLinkInsertKey value) {
    cmemlinkJNI.MemLinkInsertMkv_keylist_set(swigCPtr, this, MemLinkInsertKey.getCPtr(value), value);
  }

  public MemLinkInsertKey getKeylist() {
    long cPtr = cmemlinkJNI.MemLinkInsertMkv_keylist_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MemLinkInsertKey(cPtr, false);
  }

  public void setTail(MemLinkInsertKey value) {
    cmemlinkJNI.MemLinkInsertMkv_tail_set(swigCPtr, this, MemLinkInsertKey.getCPtr(value), value);
  }

  public MemLinkInsertKey getTail() {
    long cPtr = cmemlinkJNI.MemLinkInsertMkv_tail_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MemLinkInsertKey(cPtr, false);
  }

  public MemLinkInsertMkv() {
    this(cmemlinkJNI.new_MemLinkInsertMkv(), true);
  }

}
