/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.googlecode.memlink;

public class MemLinkScInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MemLinkScInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MemLinkScInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      cmemlink.memlink_scinfo_free(this);
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cmemlinkJNI.delete_MemLinkScInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setConncount(int value) {
    cmemlinkJNI.MemLinkScInfo_conncount_set(swigCPtr, this, value);
  }

  public int getConncount() {
    return cmemlinkJNI.MemLinkScInfo_conncount_get(swigCPtr, this);
  }

  public void setRoot(MemLinkScItem value) {
    cmemlinkJNI.MemLinkScInfo_root_set(swigCPtr, this, MemLinkScItem.getCPtr(value), value);
  }

  public MemLinkScItem getRoot() {
    long cPtr = cmemlinkJNI.MemLinkScInfo_root_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MemLinkScItem(cPtr, false);
  }

  public MemLinkScInfo() {
    this(cmemlinkJNI.new_MemLinkScInfo(), true);
  }

}
