import sys, os, subprocess

php_home = '/opt/php'

x = subprocess.Popen(php_home + '/bin/php-config --includes', stdout=subprocess.PIPE, shell=True)
php_includes = x.stdout.read().strip().split()

os.system('swig -php -o memlink_client_php.c ../c/memlink_client.i')

cflags   = '-ggdb'
includes = ['.', '../../', '../c/', '/Developer/usr/include'] + php_includes
libpath  = ['.']
libs	 = ['m']
files    = ['../../zzmalloc.c', '../../serial.c', '../../logfile.c', '../../utils.c', 
			'../c/memlink_client.c', 'memlink_client_php.c']

env = Environment(CCFLAGS=cflags, CPPPATH=includes, LIBPATH=libpath, LIBS=libs)
env.SharedLibrary("memlink", files)
